spring.application.name=RealEstate
spring.datasource.url=jdbc:mysql://localhost:3306/real_estate?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# jpa configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

# tomcat configuration
server.tomcat.max-part-count=20
server.tomcat.multipart.file-count-threshold=20
# server.servlet.session.timeout=10m

# file upload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB


# razorpay key
razorpay.key.id=rzp_test_RuvUbr2zSaWSnW
razorpay.key.secret=7von5zveIh6oQ66k3PCqXAmR

# gemini api key
gemini.api.key=AIzaSyB5-I048vjC9EIGJZYGg5FKwvnDgmAIWSQ

# mail configuration
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=sri.j.developer@gmail.com
# spring.mail.password=prva avss hekg ixnw    
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sri.j.developer@gmail.com
spring.mail.password=prvaavsshekgixnw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000
logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG


