spring.application.name=RealEstate
spring.datasource.url=********
spring.datasource.username=********
spring.datasource.password=********

# jpa configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=********

# tomcat configuration
server.tomcat.max-part-count=********
server.tomcat.multipart.file-count-threshold=********

# file upload size
spring.servlet.multipart.max-file-size=********
spring.servlet.multipart.max-request-size=********


# razorpay key
razorpay.key.id=********
razorpay.key.secret=********

# gemini api key
gemini.api.key=********

spring.mail.host=********
spring.mail.port=********
spring.mail.username=********
spring.mail.password=********
spring.mail.properties.mail.smtp.auth=********
spring.mail.properties.mail.smtp.starttls.enable=********
spring.mail.properties.mail.smtp.connectiontimeout=********
spring.mail.properties.mail.smtp.timeout=********
spring.mail.properties.mail.smtp.writetimeout=********
logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG


